// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxmslblnibfclamdilxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bXNsYmxuaWJmY2xhbWRpbHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDE0MzUsImV4cCI6MjA2MjM3NzQzNX0.U4IiSY6E9JnB-2wPaoREQjn0c8AFQkN61mkK62w4hI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);